# Generated by Django 2.2.9 on 2020-01-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchuser',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
