# Generated by Django 2.2.9 on 2020-01-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200104_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='MatchUserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_lower', models.PositiveIntegerField(default=18)),
                ('age_higher', models.PositiveIntegerField(default=62)),
                ('states', models.ManyToManyField(to='profiles.State')),
            ],
        ),
    ]
